version: '3.1'

services:
  web:
    image: robert-bo-davis/laravel-books-example
    restart: on-failure
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=books
      - DB_USERNAME=books
      - DB_PASSWORD=change_me
    volumes:
      - ./:/app/
    networks:
      - ${BOOK_NETWORK:-books}
    ports:
      - ${BOOK_PORT:-8000}:8000

  mysql:
    image: mariadb
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=change_me
      - MYSQL_DATABASE=books
      - MYSQL_USER=books
      - MYSQL_PASSWORD=change_me
    networks:
      - ${BOOK_NETWORK:-books}

networks:
  books:
  books_test:
