<?php

namespace Tests;

use Illuminate\Foundation\Testing\TestCase as BaseTestCase;

use App\Author;
use App\Book;
use App\Edition;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;

    /**
     * Our faker object
     *
     * @var \Faker\Generator
     */
    protected $faker;

    /**
     * Setup our reusable variables
     *
     * @return void
     */
    public function setUp()
    {
        parent::setUp();

        $this->faker = \Faker\Factory::create();
    }

    /**
     * Represents the base structure of an author.
     *
     * @var array
     */
    protected $author_structure = [
        'id',
        'first_name',
        'middle_name',
        'last_name',
        'birth_year',
        'death_year',
        'created_at',
        'updated_at',
    ];

    /**
     * Generates author array using faker
     *
     * @return array valid author array generated by faker
     */
    protected function fakeAuthorArray()
    {
        return [
            'first_name'  => $this->faker->firstName,
            'middle_name' => $this->faker->firstName,
            'last_name'   => $this->faker->lastName,
            'birth_year'  => $this->faker->year,
            'death_year'  => $this->faker->year,
        ];
    }

    /**
     * Represents the base structure of a book.
     *
     * @var array
     */
    protected $book_structure = [
        'id',
        'title',
        'author_id',
        'author'   => [],
        'editions' => [],
        'created_at',
        'updated_at',
    ];

    /**
     * Generates book array using faker
     *
     * @param \App\Author $author
     *
     * @return array valid book array generated by faker
     */
    protected function fakeBookArray(Author $author)
    {
        return [
            'title'     => $this->faker->sentence,
            'subtitle'  => $this->faker->sentence,
            'author_id' => $author->id,
        ];
    }

    /**
     * Represents the base structure of an edition.
     *
     * @var array
     */
    protected $edition_structure = [
        'id',
        'number',
        'title',
        'isbn',
        'book_id',
        'book' => [
            'author' => [],
        ],
        'created_at',
        'updated_at',
    ];

    /**
     * Generates edition array using faker
     *
     * @param \App\Book $book
     *
     * @return array valid book array generated by faker
     */
    protected function fakeEditionArray(Book $book)
    {
        return [
            'number'  => $this->faker->numberBetween(1, 25),
            'title'   => $this->faker->sentence,
            // mt_getrandmax is 10
            'isbn'    => '00123456' . $this->faker->randomNumber(5, true),
            'book_id' => $book->id,
        ];
    }
}
